### ISSUE TITLE
Oracle Instant Client

### ISSUE THREAD

**Issue by maasha** [jshimko/meteor-launchpad#114]
My Meteor app have a dependency on the Oracle Instant Client.

Oracle is a pain to install - you need to register, confirm, find the right bundle to download, retry, retry, retry, link and test. In short, pain.

Any ideas how to resolve this?

**Comment by jshimko** [comment]
That's a really specific use case that is definitely outside the scope of this project.  I think you'll probably have to add the install steps to your app's Dockerfile so that your dependencies get installed during the build of your app.  And I know absolutely nothing about Oracle Instant Client, so I'm afraid I can't offer much additional assistance on that.
