### ISSUE TITLE
Avoid runs process/commands as the root user which might not be permitted in OpenShift cluster

### ISSUE THREAD

**Issue by shaliko** [jshimko/meteor-launchpad#34]
When I try run docker container based on meteor-launchpad:v1.1.4 (or previous versions) getting openshift warning/error.

```
Image apinf/platform:upgrade-meteor-launchpad runs as the root user which might not be permitted by your cluster administrator.
```

It requires additional setting for the user who runs container, but in reality, in many cases, admin of cluster will not allow run the command as root user.

**Comment by jshimko** [comment]
This image doesn't use the `USER` directive in the Dockerfile (which is why Openshift is saying that), but it [runs the process as non-root](https://github.com/jshimko/meteor-launchpad/blob/master/scripts/entrypoint.sh#L29-L31) using [gosu](https://github.com/tianon/gosu).  And that is the exact same method for running as non-root that many of the official Docker images use, so you can definitely consider it secure.

However, if that's not satisfactory, you can always override the user at runtime.  

https://docs.docker.com/engine/reference/run/#/user

Just make sure to set the user to `node` because that's who owns the directory that contains the built app.

```sh
docker run --user=node -p 80:3000 -d ...
```

(I just tested that and can confirm it works fine)
