### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by ajgarn** [jshimko/meteor-launchpad#35]
Can I specify which node version to install when building a Docker image with yours as a base? And is there a reason to why you are using v4 and not v6, which is the latest LTS version?

Great work btw!

**Comment by jshimko** [comment]
You can build your own copy of `meteor-launchpad` and specify the `NODE_VERSION` in [this file](https://github.com/jshimko/meteor-launchpad/blob/master/base.dockerfile#L6), but you can't just use whatever version you want.  You have to stick with the version that Meteor currently supports.  As of right now, that's `4.x`.  Once Meteor supports something higher, it'll change here too.

I've also debated not even installing Node/npm in this image because Meteor comes packaged with the version it requires (you use it by running `meteor node` or `meteor npm`), but the scripts in this project completely delete Meteor after the build, so I went with a separate install if Node/npm.

**Comment by ajgarn** [comment]
Okay, great answer, I did not know that. Thanks!
