### ISSUE TITLE
The command '/bin/sh -c bash $BUILD_SCRIPTS_DIR/install-meteor.sh' returned a non-zero code: 1

### ISSUE THREAD

**Issue by haibo32012** [jshimko/meteor-launchpad#42]
when i try to build, i got this:
![screenshot from 2017-05-22 18 49 22](https://cloud.githubusercontent.com/assets/7117248/26304845/72bd2478-3f1f-11e7-9553-a7a1cecc01a5.png)

**Comment by jshimko** [comment]
That's either a problem with Meteor's CDN or your internet connection.  Have you tried running the build again?  That issue doesn't happen often, but I've definitely seen it.  And it's usually fixed by just starting the build again.

If you want to try to debug that a little further, you can run the Meteor installer script manually on your machine (just to confirm it works).  If it works there, it should work when the container [runs the same thing](https://github.com/jshimko/meteor-launchpad/blob/master/scripts/install-meteor.sh#L9).  

In your terminal:

```sh
curl https://install.meteor.com/ | sh
```

Since this is a network connectivity issue and doesn't appear to be a problem with this image, I'm going to close this for now.  Good luck!

**Comment by haibo32012** [comment]
@jshimko yes, Meteor installer script it works on my machine, but it didn't work in the container, i try build many times,I will try again.thanks for reply!
