### ISSUE TITLE
Building Meteor 1.6-beta.2 fails

### ISSUE THREAD

**Issue by DeciderWill** [jshimko/meteor-launchpad#46]
When trying to build a 1.6-beta.2 application it fails with Node v8.1.2. Might have something to do with npm (1.6 doesn't support npm5 at the moment, but will, what npm version does launchpad select automatically?), but doesn't explain why it cannot download the Meteor distribution...

```
[-] Installing Meteor 1.6-beta.2...

[91mDownloading Meteor distribution
[0m[91mRetrying download in 5 seconds...
[0m[91mRetrying download in 5 seconds...
[0m[91mRetrying download in 5 seconds...
[0m[91mRetrying download in 5 seconds...
[0m[91mRetrying download in 5 seconds...
[0m[91mRetrying download in 5 seconds...
[0m[91mRetrying download in 5 seconds...
[0m[91mRetrying download in 5 seconds...
[0m[91mRetrying download in 5 seconds...
[0m[91mRetrying download in 5 seconds...
[0mThe command '/bin/sh -c cd $APP_SOURCE_DIR &&             $BUILD_SCRIPTS_DIR/install-deps.sh &&             $BUILD_SCRIPTS_DIR/install-node.sh &&             $BUILD_SCRIPTS_DIR/install-phantom.sh && 						$BUILD_SCRIPTS_DIR/install-graphicsmagick.sh &&             $BUILD_SCRIPTS_DIR/install-mongo.sh &&             $BUILD_SCRIPTS_DIR/install-meteor.sh &&             $BUILD_SCRIPTS_DIR/build-meteor.sh &&             $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1
Build step 'Docker Build and Publish' marked build as failure
Taking single-use slave mesos-jenkins-431ba98af7494ee19510df176157c034 offline.
Finished: FAILURE
```

**Comment by DeciderWill** [comment]
Removed the v8.1.2 build argument and still fails to download 1.6-beta.2 on node-v4.8.3. I can download the beta locally, so I don't think it's to do with the distribution server.

**Comment by jshimko** [comment]
This has nothing to do with Node or npm.  This is a failure to install a pre-release version of Meteor. 
 Installing pre-release versions as the initial version on the machine isn't supported (in this container or on any other machine).  This image detects the version of Meteor in your app and alters Meteor's install script (from https://install.meteor.com) to download the version you need directly (instead of just downloading the latest).  The problem with that is Meteor's install script doesn't support installing pre-release versions directly.  You need to first install the latest stable version of Meteor and then it will upgrade to the pre-release.  

You can get around this by using the `jshimko/meteor-launchpad:devbuild` tag.  Since it installs and caches the latest stable version of Meteor before your app code is in the container, it will be able to do that update once your app gets copied in and the version is detected by the Meteor build tool. 

While this will at least get your build working, it also creates a huge image with Meteor still cached in it.  So it's definitely not a production solution.  But neither is installing pre-release versions of Meteor, so I guess you're all set there.  ;)

**Comment by DeciderWill** [comment]
Thanks for the prompt and detailed response, I didn't know how pre-release versions were handled.
