### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by mklueh** [jshimko/meteor-launchpad#55]
The build process is lasting very long and I´m wondering why nothing is getting cached. I´m currently using the dev image of meteor-launchpad.

> ONBUILD RUN cd $APP_SOURCE_DIR && \
>         $BUILD_SCRIPTS_DIR/install-deps.sh && \
>         $BUILD_SCRIPTS_DIR/install-node.sh && \
>         $BUILD_SCRIPTS_DIR/install-phantom.sh && \
>         $BUILD_SCRIPTS_DIR/install-graphicsmagick.sh && \
>         $BUILD_SCRIPTS_DIR/install-mongo.sh && \
>         $BUILD_SCRIPTS_DIR/install-meteor.sh && \
>         $BUILD_SCRIPTS_DIR/build-meteor.sh && \
>         $BUILD_SCRIPTS_DIR/post-build-cleanup.sh

Why does that run everytime again, and can´t that be modified to make caching possible?

It´s possible to cache NPM by doing the installation of the packages outside from the project and copy the contents into the project afterwards
```

ADD package.json /tmp/package.json
RUN cd /tmp && npm install
RUN mkdir -p /opt/app && cp -a /tmp/node_modules /opt/app/
```

Are there any reasons for not doing that in Meteor projects?

Another problem is that I install the Android SDK afterwards and it seems that doesn´t get cached either which is really a headache as it has multiple GB. 

If I understood Docker correctly, child layers need to be rebuild as soon as the parent changes.

What would be the best solution in that case? I thought about modifying meteor-launchpad and make the android docker image the base image of meteor-launchpad.

Another attempt would be caching meteor-launchpad build completely and prevent layers from changing at all, but I guess this isn´t possible because as soon as files of my application change, I need to rebuild the Meteor application anyway which leads to a rebuild of all layers again.

Do you have any advice?

**Comment by jshimko** [comment]
Sorry for the delayed response.

The reason things are set up the way they currently are is for the sake of keeping the image size down.  Once you cache a layer, there's no getting rid of that disk space (even if you delete the files in a subsequent layer).  So the reason this image does it all in one shot is because things like OS build tools, Meteor, build caches, etc. that are installed/used in the first step are not needed after the build to run the app and are a waste of disk space and network bandwidth if you keep them around.  So the tools are installed, your app gets built, and then unnecessary OS packages, Meteor, your unbuilt app code, and any other caches are all purged from the image.  This makes a huge difference in image size and the only way to get that disk space gain is by doing all of those steps in one layer with no caching.

However, I totally understand that you want something more efficient in development.  If you want something that builds faster when you're building over and over, you should use the `devbuild` tag.  See [README#development-builds](https://github.com/jshimko/meteor-launchpad#development-builds).  That will install all build tools, Meteor, etc. on the first build and then everything will then be cached for subsequent builds.  Only the `meteor build` step happens on subsequent builds.  Just note that this makes a huge final image full of things your app doesn't need anymore, so only use that while developing and then use the `:latest` tag for your official release.

You are partially right about one part though.  The `npm install` portion _could_ be cached in the `devbuild` version, but you don't want that for the production version.  The reason being that resulting `node_modules` folder full of thousands of files is never used again after the `meteor build` command.  Meteor creates a production bundle and that is the only thing that remains of your app.  For that reason, the build scripts delete your app code and all of those `node_modules` after the build.  In the same way as above, this also makes a pretty big difference in image size.

So I guess I could add that additional caching to the `devbuild`, but I'll need to refactor the Meteor build script and create one for production and one for dev.  I can look into that for the next release, but it's probably not the big time savings you're looking for.  Installing all of the OS dependencies and Meteor are the things that make the biggest difference (which `devbuild` takes care of for you already).

As for the Android build stuff, that might be outside of the scope of this image.  I think you may be better off setting up a CI build process that takes care of these two different builds.  I'm a big fan of [CircleCI](https://circleci.com/) (which is how this base image gets built and deployed to Docker Hub).  You can see the setup [here](https://github.com/jshimko/meteor-launchpad/tree/master/.circleci) and all of the build history [here](https://circleci.com/gh/jshimko/meteor-launchpad).  You'd essentially just create whatever build steps you need in the CI build process, then you can add whatever dependencies you need for Android, Java, etc. and you wouldn't need to figure out how to build that into this image somehow.  Way more manageable if you ask me.
