### ISSUE TITLE
Stopped building Docker image

### ISSUE THREAD

**Issue by occasl** [jshimko/meteor-launchpad#60]
When I try to run `docker build -t myproj:latest .` I'm getting the following error:

```
[-] Building Meteor application...

Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local

Currently, it is only possible to build iOS apps on an OS X system.
Supply the server hostname and port in the --server option for mobile app
builds.
The command '/bin/sh -c cd $APP_SOURCE_DIR &&             $BUILD_SCRIPTS_DIR/install-deps.sh &&             $BUILD_SCRIPTS_DIR/install-node.sh &&             $BUILD_SCRIPTS_DIR/install-phantom.sh && 						$BUILD_SCRIPTS_DIR/install-graphicsmagick.sh &&             $BUILD_SCRIPTS_DIR/install-mongo.sh &&             $BUILD_SCRIPTS_DIR/install-meteor.sh &&             $BUILD_SCRIPTS_DIR/build-meteor.sh &&             $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1
```
My Dockerfile is simply:
```
# Builds a Docker to deliver dist/
FROM jshimko/meteor-launchpad:latest
```

I have my launchpad.conf set as follows:
```
# launchpad.conf

# Use apt-get to install any additional dependencies
# that you need before your building/running your app
# (default: undefined)
APT_GET_INSTALL="curl git wget"

# Install a custom Node version (default: latest 4.x)
NODE_VERSION=7.10.1

# Installs the latest version of each (default: all false)
INSTALL_MONGO=false
INSTALL_PHANTOMJS=false
INSTALL_GRAPHICSMAGICK=false
```
Any ideas how to get around this?

**Comment by occasl** [comment]
This is due to the `.meteor/platforms` file containing android and ios. Those must be removed prior to running a docker build.

**Comment by jshimko** [comment]
If you're using the latest version of this image, that problem shouldn't happen because the `--server-only` flag is being used in the `meteor build` command (which is supposed to cause Meteor to ignore the mobile platform builds)

https://github.com/jshimko/meteor-launchpad/blob/master/scripts/build-meteor.sh#L22

So I would make sure to pull the latest build because I suspect you might have an older cached version.

```sh
docker pull jshimko/meteor-launchpad:latest
```

Or you can check [the current version tags](https://hub.docker.com/r/jshimko/meteor-launchpad/tags/) and use the latest one instead of the `latest` tag (which doesn't guarantee you're actually using the latest on Docker Hub when you already have a previous version of "latest" cached locally).  So you can either make sure to do a pull first or you can use a specific version number.  Either way, it's a good practice to always confirm you're using the latest build.

Also FYI, Meteor doesn't support Node 7.10.1.  You probably shouldn't adjust that value unless you're using an older version of Meteor and need an older version of Node to match it.  This project always makes sure to use the version of Node that the latest version of Meteor supports (which is currently 4.8.4).

**Comment by occasl** [comment]
Yup, I noticed that when I looked in your source. I pulled your latest since and bingo, that worked!

+1 on Meteor/Node version.

**Comment by occasl** [comment]
BTW, should I be concerned about this message that comes up? It seems to stay stuck here for awhile and then completes.

```
Even with METEOR_ALLOW_SUPERUSER or --allow-superuser, permissions in your app
directory will be incorrect if you ever attempt to perform any Meteor tasks as
a normal user. If you need to fix your permissions, run the following command
from the root of your project:

  sudo chown -Rh <username> .meteor/local
```

**Comment by jshimko** [comment]
No, that's just a warning from Meteor that can be ignored.  The app builds as root because it was WAY easier to keep things working that way.  The permissions are also [adjusted to non-root afterward](https://github.com/jshimko/meteor-launchpad/blob/master/scripts/build-meteor.sh#L37-L38) and Meteor is then deleted, so the warning is completely irrelevant in this use case.  It's really just for people that are doing builds manually as root and may not understand what that means.

And it's definitely not stuck there.  It's building your app with the `meteor build` command at that point, so the wait is expected and not related to that warning.
