### ISSUE TITLE
Using meteor-launchpad for project that also uses cordova platforms

### ISSUE THREAD

**Issue by duodeka** [jshimko/meteor-launchpad#62]
I would like to use this package to build my meteor project. The builds fail as soon as I add android and ios to the `.meteor/platforms` file, even though the `--server-only` is used in the meteor build script. 

Has encountered this problem before? Is there an easy fix?

Meanwhile I will fork this image in an attempt to fix it!

**Comment by jshimko** [comment]
Are you sure you're actually using the latest build?  This has been confirmed fixed by several people.  Try running `docker pull jshimko/meteor-launchpad:latest` before your build to confirm you definitely have it.  If anything gets pulled down, you weren't using the latest build.  

If Docker finds an image in your local cache with the same name, it won't even bother to check Docker Hub for the _actual_ latest.  It thinks you already have it.  The `:latest` tag is just a name like any other tag and is used because it's a common convention, but it definitely doesn't ensure you're actually using the latest.

For this exact reason, I'm seriously considering discontinuing the use of that tag and deleting it from Docker Hub.  This is a fairly common problem and I bet a lot of people are using really old cached copies of the image as a result.

A more thorough explanation...

http://container-solutions.com/docker-latest-confusion/

**Comment by duodeka** [comment]
Thanks @jshimko, that was it! I have not used Docker for too long, so this has never occurred to me before. Learning every day :)
