### ISSUE TITLE
Docker build of meteor-launchpad:latest on windows 10 pro 64-bit: meteor retrying download & returns non-zero code

### ISSUE THREAD

**Issue by SebastianSativa** [jshimko/meteor-launchpad#66]
Why does this not work? How in the world do I fix this?

![image](https://user-images.githubusercontent.com/9719427/30823825-d1307156-a22d-11e7-8df2-a5a4efcbed6d.png)

![image](https://user-images.githubusercontent.com/9719427/30823747-8f6f260e-a22d-11e7-8623-243d78e01367.png)

**Comment by jshimko** [comment]
It looks like you're trying to run the build command in a project that isn't a Meteor app.  Note the beginning of the error `head: cannon open...` . That can only happen when you try to run a build from an app directory that doesn't have a `.meteor/release` file.

More importantly, it looks like you're trying to use this with Reaction Commerce.  Why?  You can't just use whatever Docker base you want with Reaction.  It has [its own base](https://github.com/reactioncommerce/base) because it has custom dependencies.

**Comment by SebastianSativa** [comment]
Well Jerry, I hear you :D That's besides the point though: the point is that I simply tried to build a basic Docker image based YOUR meteor-launchpad docker image, without changing anything. The only thing I have in my Dockerfile is that line you're seeing in the first screenshot - should it not simply work like this, or have I misunderstood how to use it? Again, nevermind the Reaction-themed naming, although I see it can be quite confusing.
